name: 'build bch 24.0.0'
on: workflow_dispatch

# 需更改的位置一
# 第二个需要更改的位置: context: ./10-bch/v24.0.0/
env:
  major_version: '24'
  minor_version: '0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      patch_version: ${{ github.run_number }}
      docker_registry_aliyun_beijing: registry.cn-beijing.aliyuncs.com
      docker_registry_aliyun_hongkong: registry.cn-hongkong.aliyuncs.com
      docker_registry_aliyun_USA: registry.us-east-1.aliyuncs.com
    steps:
      - name: generate env variable
        run: |
          echo "version_tag=poolin/bch:${{ env.major_version }}.${{ env.minor_version }}" >> $GITHUB_ENV
          echo "repository=${GITHUB_REPOSITORY#iblockin/}" >> $GITHUB_ENV
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Slack notification
        uses: tiloio/slack-webhook-action@v1.0.1
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_json: '{"blocks":[{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"*Host*:ali.bj.btc-r5.common.06.poolin.com"}},{"type":"section","text":{"type":"mrkdwn","text":"*Progress*:bj6.ss01.01"}},{"type":"section","text":{"type":"mrkdwn","text":"\344\275\240\345\245\275, \346\265\213\350\257\225"}},{"type":"divider"}]}'