# 需更改的位置一 name里的名称和版本号
name: 'build stc 1.3.0'
on: workflow_dispatch

# 需更改的位置二 版本号
env:
  major_version: '1'
  minor_version: '3.0'

jobs:
  build:
    runs-on: self-hosted
    env:
      patch_version: ${{ github.run_number }}
      docker_registry_aliyun_beijing: registry.cn-beijing.aliyuncs.com
      docker_registry_aliyun_hongkong: registry.cn-hongkong.aliyuncs.com
      docker_registry_aliyun_USA: registry.us-east-1.aliyuncs.com
    steps:
      - name: generate env variable
      # 需更改的位置三 version_tag=poolin/[对应名称] 不一定为缩写
        run: |
          echo "version_tag=poolin/stc:${{ env.major_version }}.${{ env.minor_version }}" >> $GITHUB_ENV
          echo "repository=${GITHUB_REPOSITORY#iblockin/}" >> $GITHUB_ENV
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Aliyun Beijing
        uses: docker/login-action@v1
        with:
          registry: ${{ env.docker_registry_aliyun_beijing }}
          username: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_TOKEN }}
      - name: Login to Aliyun Hongkong
        uses: docker/login-action@v1
        with:
          registry: ${{ env.docker_registry_aliyun_hongkong }}
          username: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_TOKEN }}
      - name: Login to Aliyun USA
        uses: docker/login-action@v1
        with:
          registry: ${{ env.docker_registry_aliyun_USA }}
          username: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_TOKEN }}
      # 第四个需要更改的位置   
      - name: Build and push stc
      # 第五个需要更改的位置 id里的docker_build_[名称]
        id: docker_build_stc
        uses: docker/build-push-action@v2
        # 第六个需要更改的位置: context: 正确的目录位置
        with:
          context: ./26-stc/v1.3.0/
          push: true
          # 避免线上事故, 不打 latest 标签
          tags: |
            ${{ env.docker_registry_aliyun_USA }}/${{ env.version_tag }}
            ${{ env.docker_registry_aliyun_beijing }}/${{ env.version_tag }}
            ${{ env.docker_registry_aliyun_hongkong }}/${{ env.version_tag }}
      - name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          # 第7个需要更改第位置 title里边 text里面 和最后环境变量里${{ steps.docker_build_stc.outputs.digest }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title":"STC 节点构建完毕",
                "text": "# STC 节点构建完毕 # \n ### Beijing Registry ### \n > ${{ env.docker_registry_aliyun_beijing }}/${{ env.version_tag }} \n  ### Hongkong Registry ### \n > ${{ env.docker_registry_aliyun_hongkong }}/${{ env.version_tag }} \n  ### USA Registry ### \n > ${{ env.docker_registry_aliyun_USA }}/${{ env.version_tag }} \n ### Digest ### \n > ${{ steps.docker_build_stc.outputs.digest }}"
              }
            }
