name: 'build eth mev_geth 1.10.2.patch.2'
on: workflow_dispatch

# 需更改的位置一
# 第二个需要更改的位置: context: ./05-ethereum/mev-geth/mev-geth-v1.10.2.patch/
env:
  major_version: '1'
  minor_version: '10.2.patch.2'

jobs:
  build:
    runs-on: self-hosted
    env:
      patch_version: ${{ github.run_number }}
      docker_registry_aliyun_beijing: registry.cn-beijing.aliyuncs.com
      docker_registry_aliyun_hongkong: registry.cn-hongkong.aliyuncs.com
      docker_registry_aliyun_USA: registry.us-east-1.aliyuncs.com
    steps:
      - name: generate env variable
        run: |
          echo "version_tag=poolin/mev-geth:${{ env.major_version }}.${{ env.minor_version }}" >> $GITHUB_ENV
          echo "repository=${GITHUB_REPOSITORY#iblockin/}" >> $GITHUB_ENV
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Aliyun Beijing
        uses: docker/login-action@v1
        with:
          registry: ${{ env.docker_registry_aliyun_beijing }}
          username: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_TOKEN }}
      - name: Login to Aliyun Hongkong
        uses: docker/login-action@v1
        with:
          registry: ${{ env.docker_registry_aliyun_hongkong }}
          username: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_TOKEN }}
      - name: Login to Aliyun USA
        uses: docker/login-action@v1
        with:
          registry: ${{ env.docker_registry_aliyun_USA }}
          username: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_TOKEN }}
      - name: Build and push mev_geth
        id: docker_build_mev_geth
        uses: docker/build-push-action@v2
        with:
          context: ./05-ethereum/mev-geth/mev-geth-v1.10.2.patch.2/
          push: true
          # 避免线上事故, 不打 latest 标签
          tags: |
            ${{ env.docker_registry_aliyun_USA }}/${{ env.version_tag }}
            ${{ env.docker_registry_aliyun_beijing }}/${{ env.version_tag }}
            ${{ env.docker_registry_aliyun_hongkong }}/${{ env.version_tag }}
      - name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title":"ETH 节点 mev_geth 构建完毕",
                "text": "# ETH 节点 mev_geth 构建完毕 # \n ### Beijing Registry ### \n > ${{ env.docker_registry_aliyun_beijing }}/${{ env.version_tag }} \n  ### Hongkong Registry ### \n > ${{ env.docker_registry_aliyun_hongkong }}/${{ env.version_tag }} \n  ### USA Registry ### \n > ${{ env.docker_registry_aliyun_USA }}/${{ env.version_tag }} \n ### Digest ### \n > ${{ steps.docker_build_mev_geth.outputs.digest }}"
              }
            }
